apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: chamseddinedocker/crudappfrontend:prod
          # image: frontend:prod
          ports:
            - containerPort: 3000
          env:
            - name: BACKEND_URL
              value: http://backend:3700
          # imagePullPolicy: Never